#!/usr/local/bin/python3
# sudo chmod +x /Users/icepitproductions/bin/testmenu004.py
# testmenu007

from simple_term_menu import TerminalMenu
import subprocess
import os
import shutil
# from tkinter import *
# from tkinter import filedialog
# import shlex
# import sys
# import pyttsx3

subprocess.run('clear')
print(" =============================================== Icepit Productions ===============================================")
main_menu = [
  "[1] audio project",
  # "[2] image project",
  # "[3] docs project",
  # "[4] video project",
  # "[5] web project",
  "[q] quit"]
audio_project_menu = [
  "[1] Produce",
  "[2] Record",
  "[3] Mix & Master",
  "[q] Go Back"]
loop = True
while loop:
    choice = main_menu[TerminalMenu(main_menu, title = "Main menu", menu_cursor_style = ("fg_green","bold"), menu_highlight_style = ("fg_black", "bg_green"), menu_cursor = "~").show()]
    if choice == "[1] audio project":
      sub_loop = True
      while sub_loop:
        suffix = (" Project"); choice = audio_project_menu[TerminalMenu(audio_project_menu, title = "audio project menu", menu_cursor_style = ("fg_green", "bold"), menu_highlight_style = ("fg_black", "bg_green"), menu_cursor = "🔊").show()]
        if choice == "[1] Produce":
          producer_name = input("Producer : ");
          project_name = input("Project  : ");
          Project_Path = ("/Users/icepitproductions/Desktop");
          directory = (Project_Path + "/" + producer_name + " - " + project_name + " " + suffix);
          Root_Folder = os.path.join(directory);
          folder_1 = ("/audio"); folder_2 = ("/archives"); folder_3 = ("/imports"); folder_4 = ("/exports"); folder_5 = (folder_2 + "/stems"); folder_6 = (folder_4 + "/final"); folder_7 = (folder_4 + "/unused");
          os.makedirs(Root_Folder + folder_1); os.makedirs(Root_Folder + folder_2); os.makedirs(Root_Folder + folder_3); os.makedirs(Root_Folder + folder_4); os.makedirs(Root_Folder + folder_5); os.makedirs(Root_Folder + folder_6); os.makedirs(Root_Folder + folder_7); os.chdir(Root_Folder); shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.nfo',project_name + ".nfo"); Project_File_1 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.flp',project_name + ".flp"); print("FLStudio : " + Project_File_1); Project_File_2 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[ABLETON]/Macros.als',project_name + ".als"); print("Ableton  : " + Project_File_2);
          os.chdir(Root_Folder);

          # open the template
          # subprocess.run(["open", project_name + ".flp"]);
          
          # open the folder
          subprocess.run(["open", Root_Folder]);
          
          # open tools apps
          # subprocess.run(["open", Samplism]); # Samplism (/Applications/Samplism.app)
          # subprocess.run(["open", Sononym]); # Sononym (/Applications/Sononym.app)
          subprocess.run(["open", "Applications/Samplism.app"]);
          subprocess.run(["open", "Applications/Sononym.app"]);
          

          sub_loop = False; loop = False;
        elif choice == "[2] Record":

          artist_name = input("Artist         : ")
          project_name = input("Title          : ")
          Project_Path = ("/Users/icepitproductions/Desktop");
          directory = (Project_Path + "/" + producer_name + " - " + project_name + " " + suffix);
          Root_Folder = os.path.join(directory);
          # folder_1 = ("/audio"); folder_2 = ("/archives"); folder_3 = ("/imports"); folder_4 = ("/exports"); folder_5 = (folder_2 + "/stems"); folder_6 = (folder_4 + "/final"); folder_7 = (folder_4 + "/unused");
          # os.makedirs(Root_Folder + folder_1); os.makedirs(Root_Folder + folder_2); os.makedirs(Root_Folder + folder_3); os.makedirs(Root_Folder + folder_4); os.makedirs(Root_Folder + folder_5); os.makedirs(Root_Folder + folder_6); os.makedirs(Root_Folder + folder_7); os.chdir(Root_Folder); shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.nfo',project_name + ".nfo"); Project_File_1 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.flp',project_name + ".flp"); print("FLStudio : " + Project_File_1); Project_File_2 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[ABLETON]/Macros.als',project_name + ".als"); print("Ableton  : " + Project_File_2);
          os.chdir(Root_Folder);

          # subprocess.run(["open", project_name + ".flp"]);

          sub_loop = False; loop = False;
        elif choice == "[3] Mix & Master":
          artist_name = input("Artist         : ")
          project_name = input("Title          : ")
          Project_Path = ("/Users/icepitproductions/Desktop");
          directory = (Project_Path + "/" + producer_name + " - " + project_name + " " + suffix);
          Root_Folder = os.path.join(directory);
          folder_1 = ("/audio"); folder_2 = ("/archives"); folder_3 = ("/imports"); folder_4 = ("/exports"); folder_5 = (folder_2 + "/stems"); folder_6 = (folder_4 + "/final"); folder_7 = (folder_4 + "/unused");
          os.makedirs(Root_Folder + folder_1); os.makedirs(Root_Folder + folder_2); os.makedirs(Root_Folder + folder_3); os.makedirs(Root_Folder + folder_4); os.makedirs(Root_Folder + folder_5); os.makedirs(Root_Folder + folder_6); os.makedirs(Root_Folder + folder_7); os.chdir(Root_Folder); shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.nfo',project_name + ".nfo"); Project_File_1 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[FLSTUDIO]/basic.flp',project_name + ".flp"); print("FLStudio : " + Project_File_1); Project_File_2 = shutil.copyfile('/Volumes/CatalogHD/TemplateLibrary/[ABLETON]/Macros.als',project_name + ".als"); print("Ableton  : " + Project_File_2);
          os.chdir(Root_Folder);

          # subprocess.run(["open", project_name + ".flp"]);

          sub_loop = False; loop = False;
        elif choice == "[q] Go Back":
          sub_loop = False
    elif choice == "[q] quit":
        loop = False

